language: python
python:
  - "3.8"

# command to install dependencies
before-script:
  - pip install -r requirements.txt
  - psql -c 'create database travis_ci_test;' -U postgres

services:
  - postgresql

script:
  - ./manage.py test