language: python
python:
  - "3.8"

# command to install dependencies
before-script:
  - pip install -r requirements.txt
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.29.0/geckodriver-v0.29.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.29.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

services:
  - postgresql

script:
  - ./manage.py test