language: python
python:
  - "3.8"

# command to install dependencies
before-script:
  - pip install -r requirements.txt

services:
  - postgresql

env:
  - DJANGO_SETTINGS_MODULE='trailing_planner.settings.travis'

script:
  - ./manage.py test