# Generated by Django 3.2.3 on 2021-06-17 09:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weeklyObjectifKm', models.IntegerField(default=0)),
                ('weeklyObjectifD', models.IntegerField(default=0)),
                ('monthlyObjectifKm', models.IntegerField(default=0)),
                ('monthlyObjectifD', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainingDate', models.DateField(default=django.utils.timezone.now, verbose_name='Date of training')),
                ('trainingType', models.CharField(default='', max_length=40)),
                ('trainingKm', models.IntegerField(default=0)),
                ('trainingD', models.IntegerField(default=0)),
                ('trainingComments', models.CharField(default='', max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('feeling', models.IntegerField(default=0)),
                ('trainingListResume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.trainingresume')),
            ],
        ),
    ]
