# Generated by Django 3.2.3 on 2021-06-17 10:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_profil', '0010_sportprofil_cheers_up'),
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingresume',
            name='sportProfilRelated',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user_profil.sportprofil'),
        ),
        migrations.AddField(
            model_name='trainingresume',
            name='weekStartDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of training'),
        ),
    ]
