# Generated by Django 3.2.3 on 2021-06-17 10:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20210617_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingresume',
            name='weekStartDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='First day of the week'),
        ),
    ]
