# Generated by Django 3.2.3 on 2021-06-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_alter_trainingresume_weekstartdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingresume',
            name='monthlyObjectifD',
        ),
        migrations.RemoveField(
            model_name='trainingresume',
            name='monthlyObjectifKm',
        ),
        migrations.RemoveField(
            model_name='trainingresume',
            name='weekStartDate',
        ),
        migrations.RemoveField(
            model_name='trainingresume',
            name='weeklyObjectifD',
        ),
        migrations.RemoveField(
            model_name='trainingresume',
            name='weeklyObjectifKm',
        ),
        migrations.AddField(
            model_name='trainingresume',
            name='totalD',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingresume',
            name='totalKm',
            field=models.IntegerField(default=0),
        ),
    ]
