# Generated by Django 3.2.3 on 2021-06-25 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_auto_20210622_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ['trainingDate']},
        ),
    ]
