# Generated by Django 3.2.3 on 2021-06-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_alter_training_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='trainingDateWeekNb',
            field=models.IntegerField(default=0),
        ),
    ]
