# Generated by Django 3.2.3 on 2021-07-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_training_trainingdatedaystr'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='trainingDateMonthNb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='training',
            name='trainingDateYearNb',
            field=models.IntegerField(default=2021),
        ),
    ]
