# Generated by Django 3.2.3 on 2021-06-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SportProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strava_link', models.CharField(max_length=200)),
                ('final_objectif_name', models.CharField(max_length=200)),
                ('final_objectif_date', models.DateTimeField(verbose_name='Final objectif date')),
                ('final_objectif_deniv', models.IntegerField()),
                ('final_objectif_km', models.IntegerField()),
            ],
        ),
    ]
