# Generated by Django 3.2.3 on 2021-06-06 12:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportprofil',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sportprofil',
            name='final_objectif_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 6, 14, 25, 37, 797497), verbose_name='Final objectif date'),
        ),
        migrations.AlterField(
            model_name='sportprofil',
            name='final_objectif_deniv',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sportprofil',
            name='final_objectif_km',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sportprofil',
            name='final_objectif_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='sportprofil',
            name='strava_link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
