# Generated by Django 3.2.3 on 2021-06-11 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_profil', '0002_auto_20210606_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportprofil',
            name='final_objectif_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Final objectif date'),
        ),
    ]
