# Generated by Django 3.2.3 on 2021-06-11 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profil', '0007_alter_sportprofil_final_objectif_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportprofil',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
